#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Danto"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Back to Website"
    url = "https://www.akhil.sh/"
    weight = 1

  [[menu.main]]
    name = "Blogs Home"
    url = "/"
    weight = 2

  [[menu.main]]
    name = "All Blogs"
    url = "/posts/"
    weight = 3

  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "https://www.akhil.sh/contact-us"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/3.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/3.png"
  description = "Danto is a news and magazine Hugo theme"
  color_scheme = "dark" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "One stop for blogs about LLMs, cybersecurity and AI Published Weekly."
    hero__description = "Get deep knowledge on building projects using LLMs and AI. Also features blogs on cybersecurity. Get killer insights, tips and tricks."


  #-------------------------------
  # Tags Section Settings




  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = true
    section_title = "Meet our author"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  # Social Links

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "Youtube"
    link = "https://www.youtube.com/@AkhilSharmaTech"

  [[params.social]]
    icon = "fa-brands fa-discord"
    name = "Facebook"
    link = "https://discord.com/invite/WFA6YhJAKb"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com/AkhilAiri"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com/AkhilSharma90"  

  [[params.social]]
    icon = "fa-brands fa-medium"
    name = "Youtube"
    link = "https://medium.com/@akhilsharma_10270"

  # Other icons can be found at https://fontawesome.com/icons


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false